### PR TITLE
[ ci ] first attempt at github actions

### PR DESCRIPTION
**Pull request by gallais**

### CODE REVIEW

**Comment by JacquesCarette** [comment]
Looks fantastic. And agda-categories can actually typecheck with that little memory?

**Comment by gallais** [comment]
> agda-categories can actually typecheck with that little memory?

I did not know it was impossible so I did it. :rofl:

**Comment by JacquesCarette** [comment]
It used to need 6M, so something has improved!

**Comment by gallais** [comment]
Github actions runs out of memory if we compile Agda with `-O2` so we're forced to
only pass `-O1` to `ghc`. Could it be that the more optimised version of the compiler
also uses more memory when typechecking `agda-categories`?

**Comment by JacquesCarette** [comment]
Hmm, that's possible.

Odd thing: I see this as a PR on gallais/agda-categories but not agda/agda-categories?

**Comment by gallais** [comment]
Yeah I wanted to clean it up a bit before opening it on agda-categories.
It should arrive later today.

**Pull request closed without merging**
